### PR TITLE
Set options for complex pinentry programs

### PR DESCRIPTION
**Pull request by ebroder**
At least on Linux, without passing the display, ttyname, and ttytype
options, the pinentry program errors out when it tries to actually
display the pinentry program.

The list of options was taken from sketching on the set of options
that `gpg` passes to the agent - it's possible that LC_TYPE and
LC_MESSGAES aren't necessary, but I wasn't able to test all of the
pinentry alternative implementations.

### CODE REVIEW

**Comment by bef** [comment]
Are there any advantages to using the same options in gpg-agent.conf - display, ttyname, lc-ctype, ...?

**Comment by ebroder** [comment]
I'm not sure I follow? If the question is whether these options should live in a config file instead of in the scd-pkcs11 code, I don't think that would make sense - all of these options are going to be session dependent, so there's no way you could know the right values in advance to put in a config file.

**Comment by bef** [comment]
Here is how it works for me:
1. user logs in locally
2. gpg-agent is started for this particular user, e.g. via .xsession or some other mechanism
-- At this point, the user already knows what appropriate values for `display`, `ttyname`, ... should be, so gpg-agent is started with the corresponding command line options `--display` and so on. Alternatively some static or default values can reside in gpg-agent.conf.

Setting `OPTIONS` within the assuan session would override the already correct values determined at login time, unless these options would not be available prior to using scd-pkcs11. To clarify the original question: Are correct values for these options available at login time - or rather at the time gpg-agent is started?

**Comment by ebroder** [comment]
Ah, sure, I see what you mean.

I'm not sure that I can put environment variables in my `gpg-agent`, and I'd have to modify the startup script provided by my OS to provide them manually. Additionally, because the `ttyname` varies based on which terminal window I use, it wouldn't be possible to supply that at startup.

Regardless of whether or not the agent should be able to discover DISPLAY on its own, I don't think there's any reasonable world in which it can figure out the current tty without having it passed in (since if I open an xterm that will be a different tty from the overall session). Given that this is what `gpg` itself does, I'm not sure I see the harm in passing them all in.

**Comment by bef** [comment]
Ok. I agree, that setting these options should be made available somehow. However, your implementation does not take malicious or unreasonable values into account. E.g. values may contain newline characters: Even though assuan_transact cuts the strict at the first occurrence of \n, it should not  even have been passed in the first place. Also, /dev/tty may not be available or named differently in non-Linux operating systems. Also, failing on error after setting an option without debugging output makes debugging rather hard. And I would like to suggest a compile time flag to enable/disable the option passing feature.

After further consideration I'm not quite sure why we would not allow the user to set `xauthority` as well, or even let the user choose which option to pass to the gpg-agent, e.g. by setting an environment variable listing all options to be set. There may be useful `SCD OPTIONS`, too.

Anyway, thank you. I will take your pull request as a suggestion and concoct a suitable alternative.

**Comment by bef** [comment]
While researching for this feature, I came across the following command on https://www.gnupg.org/documentation/manuals/gnupg/Common-Problems.html which will (re-)set "GPG_TTY", "DISPLAY", "TERM", "XAUTHORITY" and "PINENTRY_USER_DATA"

```
echo UPDATESTARTUPTTY | gpg-connect-agent
```

Also, gpg's call-pinentry.c sets ttyname, ttytype and lc-\* when calling start_pinentry.

After some consideration, your proposed solution is probably the most convenient way to handle options. I will go ahead and add a slightly modified version.

**Comment by bef** [comment]
Apparently the only "SCD OPTION" available is `event-signal`, which is not relevant for us. Other OPTIONs can now be set.

**Comment by ebroder** [comment]
Awesome, thanks for looking into that. For what it's worth, I'm now seeing build failures because my libgpg-error doesn't include gpgrt_asprintf (Ubuntu 14.04). My libc does include a native asprintf, though, so I think some sort of autoconf magic would work here.

**Comment by bef** [comment]
It compiles on ubuntu now. Apparently old versions libgpg-error lack gpgrt_\* functions.

**Pull request closed without merging**
